<?php

namespace FrontEndBundle\Repository;

/**
 * RegioneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegioneRepository extends \Doctrine\ORM\EntityRepository
{
}
