<?php

namespace FrontEndBundle\Repository;

/**
 * SegnalazioneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SegnalazioneRepository extends \Doctrine\ORM\EntityRepository
{
}
