<?php

namespace FrontEndBundle\Repository;

/**
 * Tipo_GustoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Tipo_GustoRepository extends \Doctrine\ORM\EntityRepository
{
}
