front_end:
    resource: "@FrontEndBundle/Resources/config/routing.yml"
    prefix:   /

back_end:
    resource: "@BackEndBundle/Resources/config/routing.yml"
    prefix:   /admin

#Ho commentato la rotta di default affinché venisse sovrascritta dal FrontEndBundle
# app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
