homepage:
    path:     /
    defaults: { _controller: FrontEndBundle:Default:index }

search:
    path:     /search
    defaults: { _controller: FrontEndBundle:Default:search }

favorites:
    path:     /favorites
    defaults: { _controller: FrontEndBundle:Default:favorite }

front_settings:
    path:     /settings
    defaults: { _controller: FrontEndBundle:Default:password_settings }

settings_password:
    path:     /settings_password
    defaults: { _controller: FrontEndBundle:Default:password_settings }

settings_city:
    path:     /settings_city
    defaults: { _controller: FrontEndBundle:Default:city_settings }

segnala:
    path:     /segnala
    defaults: { _controller: FrontEndBundle:Footer:segnala }

segnalaProvincia:
    path:     /segnalaProvincia/{id}
    defaults: { _controller: FrontEndBundle:Footer:segnalaProvincia }

segnalaCitta:
    path:     /segnalaCitta/{id}
    defaults: { _controller: FrontEndBundle:Footer:segnalaCitta }

segnalaGelateria:
    path:     /segnalaGelateria/{id}
    defaults: { _controller: FrontEndBundle:Footer:segnalaGelateria }

chisiamo:
    path:     /chisiamo
    defaults: { _controller: FrontEndBundle:Footer:chisiamo }

privacy:
    path:     /privacy
    defaults: { _controller: FrontEndBundle:Footer:privacy }

contatti:
    path:     /contatti
    defaults: { _controller: FrontEndBundle:Footer:contatti }

contatta:
    path:     /contatta
    defaults: { _controller: FrontEndBundle:Footer:contatta }

hpprovincefilter:
    path:     /hpprovincefilter/{id}
    defaults: { _controller: FrontEndBundle:Default:hpProvinceFilter }

hpcityfilter:
    path:     /hpcityfilter/{id}
    defaults: { _controller: FrontEndBundle:Default:hpCityFilter }

searchprovincefilter:
    path:     /searchprovincefilter/{id}
    defaults: { _controller: FrontEndBundle:Default:searchProvinceFilter }

searchcityfilter:
    path:     /searchcityfilter/{id}
    defaults: { _controller: FrontEndBundle:Default:searchCityFilter }
