_homepage:
    path:     /
    defaults: { _controller: FrontEndBundle:Default:index }

_search:
    path:     /search
    defaults: { _controller: FrontEndBundle:Default:search }

_favorites:
    path:     /favorites
    defaults: { _controller: FrontEndBundle:Default:favorite }

segnala:
    path:     /segnala
    defaults: { _controller: FrontEndBundle:Footer:segnala }

chisiamo:
    path:     /chisiamo
    defaults: { _controller: FrontEndBundle:Footer:chisiamo }

privacy:
    path:     /privacy
    defaults: { _controller: FrontEndBundle:Footer:privacy }

contatti:
    path:     /contatti
    defaults: { _controller: FrontEndBundle:Footer:contatti }
