admin:
    path:     /
    defaults: { _controller: BackEndBundle:Admin:settings }

settings:
    path:     settings
    defaults: { _controller: BackEndBundle:Admin:settings }

changePsw:
    path:     settings/changePsw
    defaults: { _controller: BackEndBundle:Admin:changePsw }

changeMail:
    path:     settings/changeMail
    defaults: { _controller: BackEndBundle:Admin:changeMail }

provinceFilter:
    path:     settings/provinceFilter/{id}
    defaults: { _controller: BackEndBundle:Admin:provinceFilter }

cityFilter:
    path:     settings/cityFilter/{id}
    defaults: { _controller: BackEndBundle:Admin:cityFilter }

favoriteCity:
    path:     settings/favoriteCity
    defaults: { _controller: BackEndBundle:Admin:FavoriteCity }

admin_manage:
    path:     adminManage
    defaults: { _controller: BackEndBundle:Admin:adminManage }

add_admin:
    path:     addAdmin
    defaults: { _controller: BackEndBundle:Admin:addAdmin }

del_admin:
    path:     delAdmin
    defaults: { _controller: BackEndBundle:Admin:delAdmin }

add_gel:
    path:     addGel
    defaults: { _controller: BackEndBundle:Admin:addGel }

upd_gel:
    path:     updGel
    defaults: { _controller: BackEndBundle:Admin:updGel }

upd_gelProvince:
    path:     updGelProvince/{id}
    defaults: { _controller: BackEndBundle:Admin:updGelProvince }

upd_gelCitta:
    path:     updGelCitta/{id}
    defaults: { _controller: BackEndBundle:Admin:updGelCitta }

upd_gelList:
    path:     updGelList/{id}
    defaults: { _controller: BackEndBundle:Admin:updGelList }

upd_gel2:
    path:     updGel2
    defaults: { _controller: BackEndBundle:Admin:updGel2 }

upd_gel3:
    path:     updGel/3
    defaults: { _controller: BackEndBundle:Admin:updGel3 }

add_flavour:
    path:     addFlavour
    defaults: { _controller: BackEndBundle:Admin:addFlavour }

upd_flavour:
    path:     updFlavour
    defaults: { _controller: BackEndBundle:Admin:updFlavour }

upd_flavourForm:
    path:     updFlavour/{id}
    defaults: { _controller: BackEndBundle:Admin:updFlavourForm }

editagusto:
    path:     editagusto
    defaults: { _controller: BackEndBundle:Admin:editaGusto }

del_flavourForm:
    path:     delFlavourForm
    defaults: { _controller: BackEndBundle:Admin:delFlavourForm }

del_flavour:
    path:     delFlavour
    defaults: { _controller: BackEndBundle:Admin:delFlavour }

dashboard:
    path:     dashboard
    defaults: { _controller: BackEndBundle:Admin:dashboard }

dashboardprovincefilter:
    path:     dashboardprovincefilter/{id}
    defaults: { _controller: BackEndBundle:Admin:dashboardProvinceFilter }

dashboardcityfilter:
    path:     dashboardcityfilter/{id}
    defaults: { _controller: BackEndBundle:Admin:dashboardCityFilter }

report:
    path:     report
    defaults: { _controller: BackEndBundle:Admin:Report }

login2:
    path:     login
    defaults: { _controller: FOSUserBundle:Security:login }

success:
    path: success
    defaults: { _controller: BackEndBundle:Admin:success}

failure:
    path: failure
    defaults: { _controller: BackEndBundle:Admin:failure}
