settings:
    path:     settings
    defaults: { _controller: BackEndBundle:Admin:settings }

admin_manage:
    path:     adminManage
    defaults: { _controller: BackEndBundle:Admin:adminManage }

add_gel:
    path:     addGel
    defaults: { _controller: BackEndBundle:Admin:addGel }

add_gel2:
    path:     addGel/2
    defaults: { _controller: BackEndBundle:Admin:addGel }

upd_gel:
    path:     updGel
    defaults: { _controller: BackEndBundle:Admin:updGel }

sig_gel:
    path:     sigGel
    defaults: { _controller: BackEndBundle:Admin:sigGel }

add_flavour:
    path:     addFlavour
    defaults: { _controller: BackEndBundle:Admin:addFlavour }

upd_flavour:
    path:     updFlavour
    defaults: { _controller: BackEndBundle:Admin:updFlavour }

del_flavour:
    path:     delFlavour
    defaults: { _controller: BackEndBundle:Admin:delFlavour }

dashboard:
    path:     dashboard
    defaults: { _controller: BackEndBundle:Admin:dashboard }
